#!/usr/bin/env bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"
source config.sh
PORT=${PORT:-7888}

server () {
  ssh root@$SERVER "$@"
}

trench () {
  server trench -p $PORT -e "$@"
}

run () {
  mkdir -p target/resources
  npm install
  for dir in themes/*; do
    if [ -f "$dir"/package.json ]; then
      (cd "$dir" && npm install)
    fi
  done
  clj "$@" \
    -J-XX:-OmitStackTraceInFastThrow \
    -M -m $MAIN_NS --port $PORT --middleware '[cider.nrepl/cider-middleware]'
}

css () {
  npx tailwindcss \
    -c resources/tailwind.config.js \
    -i resources/tailwind.css \
    -o target/resources/public/css/main.css \
    "$@"
}

dev () {
  echo $PORT > .nrepl-port
  css --watch <<< "" &
  BIFF_ENV=dev run
}

format () {
  echo '{submit-tx [[:inner 0]]}' > cljfmt-indentation.edn
  clojure -Sdeps '{:deps {cljfmt {:mvn/version "0.8.2"}}}' -M -m cljfmt.main fix --indents cljfmt-indentation.edn
  rm cljfmt-indentation.edn
}

clean () {
  rm -rf target
}

post-receive () {
  run -P
  sudo systemctl reset-failed app.service
  sudo systemctl restart app
}

deploy () {
  css --minify
  chmod 600 config.* secrets.edn
  rsync -a --relative --exclude node_modules config.* secrets.edn themes \
    target/resources/public/css/main.css \
    app@$SERVER:
  time git push --force $DEPLOY_TO $DEPLOY_FROM
}

soft-deploy () {
  css --minify
  chmod 600 config.* secrets.edn
  rsync -a --relative --info=name1 --delete \
    --exclude node_modules \
    config.* \
    secrets.edn \
    themes \
    deps.edn \
    task \
    src \
    resources \
    target/resources/public/css/main.css \
    app@$SERVER:
  trench '"('$SOFT_DEPLOY_FN' @com.biffweb/system)"'
}

refresh () {
  trench '"(com.biffweb/refresh)"'
}

restart () {
  server systemctl reset-failed app.service
  server systemctl restart app
}

auto-soft-deploy () {
  soft-deploy
  fswatch -orl 0.1 --event=Updated --event=Removed --allow-overflow . | while read changed ; do
    soft-deploy
  done
}

logs () {
  ssh root@$SERVER journalctl -u app -f -n ${1:-300}
}

prod-repl () {
  echo Connect to nrepl port $PORT
  echo $PORT > .nrepl-port
  ssh -NL $PORT:localhost:$PORT root@$SERVER
}

prod-dev () {
  if ! which fswatch > /dev/null; then
    echo '`fswatch` command not found. Please install it: https://emcrisostomo.github.io/fswatch/getting.html'
    echo ' - Ubuntu: sudo apt install fswatch'
    echo ' - Mac: brew install fswatch'
    exit 1
  fi
  trap 'kill %1; kill %2' SIGINT
  prod-repl &
  auto-soft-deploy &
  logs
}

backup () {
  file=platypub-$(date -u "+%Y-%m-%d_%H-%M-%S").tar.gz
  ssh app@$SERVER mkdir -p storage/backups
  ssh app@$SERVER tar -cvzf storage/backups/$file storage/xtdb/
  mkdir -p storage/backups
  scp app@$SERVER:storage/backups/$file storage/backups/$file
}

"$@"
