#!/usr/bin/env bash
set -e

dev () {
  trap 'kill %1' SIGINT
  npx chokidar '**/*' --initial \
      -i 'public' \
      -i 'netlify/functions/config.json' \
      -i '.netlify' \
      -i 'tailwind.config.js' \
      -i 'node_modules' \
      -c 'rm -rf public && ./render-site' &
  netlify dev -d public
}

"$@"
